name: UI tests of online shop

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: 'Choose target'
        required: true
        default: 'chrome-browser'
        type: choice
        options:
          - chrome-browser
          - firefox-browser

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Checkout (copy) gh-pages repository to GitHub runner
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: ./.github/gh-pages

      - name: Run tests via docker-compose in chrome
        env:
          USERNAME: ${{ secrets.USERNAME }}
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
        if: github.event.inputs.deployment_target == 'chrome-browser'
        run: |
          docker compose up run_tests_in_chrome --exit-code-from run_tests || true

      - name: Run tests via docker-compose in firefox
        env:
          USERNAME: ${{ secrets.USERNAME }}
          LOGIN: ${{ secrets.LOGIN }}
          PASSWORD: ${{ secrets.PASSWORD }}
        if: github.event.inputs.deployment_target == 'firefox-browser'
        run: |
          docker compose up run_tests_in_firefox --exit-code-from run_tests || true

      - name: Copy history from gh-pages to allure-results
        run: |
          sudo mkdir -p allure-results/history  # Создает директорию для истории Allure
          sudo cp -R ./.github/gh-pages/history/* allure-results/history/
        continue-on-error: true

      - name: Generate Allure report after test in chrome browser
        if: github.event.inputs.deployment_target == 'chrome-browser'
        run: |
          sudo docker compose run un_tests_in_chrome /bin/sh -c "allure generate allure-results --clean -o allure-report"
      - name: Generate Allure report after test in firefox browser
        if: github.event.inputs.deployment_target == 'firefox-browser'
        run: |
          sudo docker compose run un_tests_in_firefox /bin/sh -c "allure generate allure-results --clean -o allure-report"

      - name: Update Allure history
        run: |
          sudo cp -R allure-report/history/* ./.github/gh-pages/history/
        continue-on-error: true

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.CI_TOKEN }}
          branch: gh-pages
          folder: allure-report
          clean: true
